<?php

namespace App\Http\Controllers;

use App\Models\Invoice;
use Dompdf\Dompdf;


class InvoiceController extends Controller
{
    public function show(Invoice $record)
    {
        ini_set("display_errors", true);
        ini_set("error_log", "phperr.log");
        ini_set("log_errors", true);
        error_reporting(E_ALL);

        $_dompdf_show_warnings = true; // record warnings generated by Dompdf
        $_dompdf_debug = false; // output frame details for every frame in the document
        $_DOMPDF_DEBUG_TYPES = [
            'page-break' => false // record information about page break determination
        ];

        $html = view('pdf.invoice', ['data' => $record])->render();

        $tmp = sys_get_temp_dir();

        $dompdf = new Dompdf([

            "logOutputFile" => "log.html",
            "debugPng" => false, // extra messaging
            "debugKeepTemp" => false, // don't delete temp files
            'debugCss' => false, // output Style parsing information and frame details for every frame in the document
            'debugLayout' => false, // draw boxes around frames
            'debugLayoutLines' => false, // line boxes
            'debugLayoutBlocks' => false, // block frames
            'debugLayoutInline' => false, // inline frames
            'debugLayoutPaddingBox' => false, // padding box

            'isRemoteEnabled' => true,
            'fontDir' => $tmp,
            'fontCache' => $tmp,
            'tempDir' => $tmp,
            'chroot' => $tmp,
        ]);

        $dompdf->loadHtml($html);

        $dompdf->render();

        $dompdf->stream('test.pdf', [
            'compress' => false,
            'Attachment' => false,
        ]);
        exit();
    }
}
